[package]
name = "pipeline-gen"
version = "1.0.1"
edition = "2024"

description = "Pipeline-gen is designed to be lightweight, easy to understand, and ready to grow with custom processing logic"

license = "MIT"

[dependencies]
reqwest = "0.13.4"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
quick-xml = { version = "0.36", features = ["serialize"] }
anyhow = "1.0.104"
