[package]
name = "pipeline-gen"
version = "1.3.3"
edition = "2024"

description = "Repository and pipelines setup in less than a minute"
repository = "https://github.com/lukas-sgx/pipeline-gen"
license = "MIT"
authors = ["lukas-sgx <lukas.soigneux@epitech.eu>"]

[dependencies]
reqwest = "0.13.4"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
quick-xml = { version = "0.41", features = ["serialize"] }
anyhow = "1.0.104"
indicatif = "0.18.6"
colorized = "1.0.0"

[profile.release]
strip = true
opt-level = "z"
codegen-units = 1

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
